# Generated by Django 4.1.7 on 2023-02-22 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='lang',
            field=models.CharField(choices=[('ru', 'Russian'), ('en', 'English'), ('de', 'German'), ('es', 'Spanish'), ('fr', 'French'), ('it', 'Italian')], default='ru', help_text='Выберите язык, на котором написана книга.', max_length=2),
        ),
    ]
