# Generated by Django 4.1.7 on 2023-02-28 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_author_options_alter_book_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['status'], 'permissions': (('can_mark_returned', 'Set book as returned'),), 'verbose_name': 'Копия', 'verbose_name_plural': 'Копии'},
        ),
    ]
